apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
  labels:
    app.kubernetes.io/instance: example06
  name: grafana-notify
  namespace: example06
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - command:
            - sleep
            - '10'
          image: alpine
          name: dummy-run
      restartPolicy: Never
